#!/usr/bin/env bash

set -e

tool_source="${BASH_SOURCE[0]}"
while [ -h "$tool_source" ] ; do tool_source="$(readlink "$tool_source")"; done
sdlc_dir="$( cd -P "$( dirname "$tool_source" )" && pwd )"
prj_home="$( cd -P "$( dirname "$sdlc_dir" )" && pwd )"

cd "${prj_home}"

hash mvn 2>/dev/null || {
  echo 'No Maven executable: aborting'
  exit 1
}

echo '---'
echo '--- Plugins updates'
mvn -Dmaven.version.ignore='(?i).*-(alpha|beta|m|rc)([-.]?\d+)?' \
    org.codehaus.mojo:versions-maven-plugin:2.18.0:display-plugin-updates \
    | grep --color=never '\[INFO\]   ' | sort | uniq
echo '--- Dependencies updates'
mvn -Dmaven.version.ignore='(?i).*-(alpha|beta|m|rc)([-.]?\d+)?' \
    org.codehaus.mojo:versions-maven-plugin:2.18.0:display-dependency-updates \
    | grep --color=never '\[INFO\]   ' | sort | uniq
echo '---'

